# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60db331e5928fb62eeb4cc36c6771ef2e004d519caca4c5bed535e9a6ea2c9166dc4c8bfca3d6850724683dd4740c5827e71be61d54d32ebcfe8b491708e43a6

test:
  secret_key_base: 73cfd8347c5d4b324600380d104227856ab726bc8e2fd32493289c8f7d2989acc34b1ecfc535a7e44ddbb503b408fc8aedb82a7485d456cfcbe04df0c777482a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
